// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package db

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, slug, timestamp_id, platform_id)
VALUES (?, ?, ?, ?)
RETURNING id, slug, timestamp_id, platform_id
`

type CreateCourseParams struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	TimestampID int64  `json:"timestamp_id"`
	PlatformID  string `json:"platform_id"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Courses, error) {
	row := q.db.QueryRowContext(ctx, createCourse,
		arg.ID,
		arg.Slug,
		arg.TimestampID,
		arg.PlatformID,
	)
	var i Courses
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TimestampID,
		&i.PlatformID,
	)
	return i, err
}

const createCourseURL = `-- name: CreateCourseURL :one
INSERT INTO course_urls (course_id, url, category, position)
VALUES (?, ?, ?, ?)
RETURNING id, course_id, url, category, position
`

type CreateCourseURLParams struct {
	CourseID string `json:"course_id"`
	Url      string `json:"url"`
	Category string `json:"category"`
	Position int64  `json:"position"`
}

func (q *Queries) CreateCourseURL(ctx context.Context, arg CreateCourseURLParams) (CourseUrls, error) {
	row := q.db.QueryRowContext(ctx, createCourseURL,
		arg.CourseID,
		arg.Url,
		arg.Category,
		arg.Position,
	)
	var i CourseUrls
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Url,
		&i.Category,
		&i.Position,
	)
	return i, err
}

const createPlatform = `-- name: CreatePlatform :one
INSERT INTO platforms (id, title, url)
VALUES (?, ?, ?)
RETURNING id, title, url
`

type CreatePlatformParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Url   string `json:"url"`
}

func (q *Queries) CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platforms, error) {
	row := q.db.QueryRowContext(ctx, createPlatform, arg.ID, arg.Title, arg.Url)
	var i Platforms
	err := row.Scan(&i.ID, &i.Title, &i.Url)
	return i, err
}

const createTimestamp = `-- name: CreateTimestamp :one
INSERT INTO timestamps (first, rest)
VALUES (?, ?)
RETURNING id, first, rest
`

type CreateTimestampParams struct {
	First int64 `json:"first"`
	Rest  int64 `json:"rest"`
}

func (q *Queries) CreateTimestamp(ctx context.Context, arg CreateTimestampParams) (Timestamps, error) {
	row := q.db.QueryRowContext(ctx, createTimestamp, arg.First, arg.Rest)
	var i Timestamps
	err := row.Scan(&i.ID, &i.First, &i.Rest)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE
FROM courses
WHERE id = ?
`

func (q *Queries) DeleteCourse(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const deleteCourseURL = `-- name: DeleteCourseURL :exec
DELETE
FROM course_urls
WHERE id = ?
`

func (q *Queries) DeleteCourseURL(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCourseURL, id)
	return err
}

const deletePlatform = `-- name: DeletePlatform :exec
DELETE
FROM platforms
WHERE id = ?
`

func (q *Queries) DeletePlatform(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlatform, id)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, slug, timestamp_id, platform_id
FROM courses
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCourse(ctx context.Context, id string) (Courses, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Courses
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TimestampID,
		&i.PlatformID,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, timestamp_id, platform_id
FROM courses
WHERE slug = ?
LIMIT 1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Courses, error) {
	row := q.db.QueryRowContext(ctx, getCourseBySlug, slug)
	var i Courses
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TimestampID,
		&i.PlatformID,
	)
	return i, err
}

const getCourseURLs = `-- name: GetCourseURLs :many
SELECT id, course_id, url, category, position
FROM course_urls
WHERE course_id = ?
ORDER BY position
`

func (q *Queries) GetCourseURLs(ctx context.Context, courseID string) ([]CourseUrls, error) {
	rows, err := q.db.QueryContext(ctx, getCourseURLs, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseUrls
	for rows.Next() {
		var i CourseUrls
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Url,
			&i.Category,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlatform = `-- name: GetPlatform :one
SELECT id, title, url
FROM platforms
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPlatform(ctx context.Context, id string) (Platforms, error) {
	row := q.db.QueryRowContext(ctx, getPlatform, id)
	var i Platforms
	err := row.Scan(&i.ID, &i.Title, &i.Url)
	return i, err
}

const getTimestamp = `-- name: GetTimestamp :one
SELECT id, first, rest
FROM timestamps
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTimestamp(ctx context.Context, id int64) (Timestamps, error) {
	row := q.db.QueryRowContext(ctx, getTimestamp, id)
	var i Timestamps
	err := row.Scan(&i.ID, &i.First, &i.Rest)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, timestamp_id, platform_id
FROM courses
ORDER BY id
`

func (q *Queries) ListCourses(ctx context.Context) ([]Courses, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Courses
	for rows.Next() {
		var i Courses
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TimestampID,
			&i.PlatformID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatforms = `-- name: ListPlatforms :many
SELECT id, title, url
FROM platforms
ORDER BY title
`

func (q *Queries) ListPlatforms(ctx context.Context) ([]Platforms, error) {
	rows, err := q.db.QueryContext(ctx, listPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Platforms
	for rows.Next() {
		var i Platforms
		if err := rows.Scan(&i.ID, &i.Title, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET slug         = ?,
    timestamp_id = ?,
    platform_id  = ?
WHERE id = ?
RETURNING id, slug, timestamp_id, platform_id
`

type UpdateCourseParams struct {
	Slug        string `json:"slug"`
	TimestampID int64  `json:"timestamp_id"`
	PlatformID  string `json:"platform_id"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Courses, error) {
	row := q.db.QueryRowContext(ctx, updateCourse,
		arg.Slug,
		arg.TimestampID,
		arg.PlatformID,
		arg.ID,
	)
	var i Courses
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TimestampID,
		&i.PlatformID,
	)
	return i, err
}

const updateCourseURL = `-- name: UpdateCourseURL :exec
UPDATE course_urls
SET url      = ?,
    category = ?,
    position = ?
WHERE id = ?
`

type UpdateCourseURLParams struct {
	Url      string `json:"url"`
	Category string `json:"category"`
	Position int64  `json:"position"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateCourseURL(ctx context.Context, arg UpdateCourseURLParams) error {
	_, err := q.db.ExecContext(ctx, updateCourseURL,
		arg.Url,
		arg.Category,
		arg.Position,
		arg.ID,
	)
	return err
}

const updatePlatform = `-- name: UpdatePlatform :one
UPDATE platforms
SET title = ?,
    url   = ?
WHERE id = ?
RETURNING id, title, url
`

type UpdatePlatformParams struct {
	Title string `json:"title"`
	Url   string `json:"url"`
	ID    string `json:"id"`
}

func (q *Queries) UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) (Platforms, error) {
	row := q.db.QueryRowContext(ctx, updatePlatform, arg.Title, arg.Url, arg.ID)
	var i Platforms
	err := row.Scan(&i.ID, &i.Title, &i.Url)
	return i, err
}
