// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type CourseUrls struct {
	ID       int64  `json:"id"`
	CourseID string `json:"course_id"`
	Url      string `json:"url"`
	Category string `json:"category"`
	Position int64  `json:"position"`
}

type Courses struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	TimestampID int64  `json:"timestamp_id"`
	PlatformID  string `json:"platform_id"`
}

type Platforms struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Url   string `json:"url"`
}

type Timestamps struct {
	ID    int64 `json:"id"`
	First int64 `json:"first"`
	Rest  int64 `json:"rest"`
}
