// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Courses, error)
	CreateCourseURL(ctx context.Context, arg CreateCourseURLParams) (CourseUrls, error)
	CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platforms, error)
	CreateTimestamp(ctx context.Context, arg CreateTimestampParams) (Timestamps, error)
	DeleteCourse(ctx context.Context, id string) error
	DeleteCourseURL(ctx context.Context, id int64) error
	DeletePlatform(ctx context.Context, id string) error
	GetCourse(ctx context.Context, id string) (Courses, error)
	GetCourseBySlug(ctx context.Context, slug string) (Courses, error)
	GetCourseURLs(ctx context.Context, courseID string) ([]CourseUrls, error)
	GetPlatform(ctx context.Context, id string) (Platforms, error)
	GetTimestamp(ctx context.Context, id int64) (Timestamps, error)
	ListCourses(ctx context.Context) ([]Courses, error)
	ListCoursesWithPlatforms(ctx context.Context) ([]ListCoursesWithPlatformsRow, error)
	ListPlatforms(ctx context.Context) ([]Platforms, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Courses, error)
	UpdateCourseURL(ctx context.Context, arg UpdateCourseURLParams) error
	UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) (Platforms, error)
}

var _ Querier = (*Queries)(nil)
